baseURL = "https://example.com"
languageCode = 'en-us'
title = "Example Site"
theme = "nostyleplease"

[params]
  [params.theme_config]
    back_home_text = ".."
    date_format = "2006-01-02"

[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
